{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) (or .Values.auth.adminPassword .Values.auth.jwtSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubebolt.fullname" . }}-auth
  labels:
    {{- include "kubebolt.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.adminPassword }}
  admin-password: {{ .Values.auth.adminPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.jwtSecret }}
  jwt-secret: {{ .Values.auth.jwtSecret | b64enc | quote }}
  {{- end }}
{{- end }}
