{{- if .Values.metrics.alertRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "kubebolt.fullname" . }}-alerts
  labels:
    {{- include "kubebolt.labels" . | nindent 4 }}
    {{- with .Values.metrics.alertRules.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
{{ .Files.Get "files/kubebolt-alerts.yaml" | indent 2 }}
{{- end }}
