apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubebolt.fullname" . }}
  labels:
    {{- include "kubebolt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.web.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "kubebolt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubebolt.fullname" . }}-api
  labels:
    {{- include "kubebolt.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
      name: api
  selector:
    {{- include "kubebolt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
