apiVersion: v2
name: kubebolt-agent
description: KubeBolt node agent — Mode A (kubelet stats + Hubble) + Mode C (read managed Prom) + SPDY-tunneled K8s API proxy with 3-tier RBAC
type: application
version: 1.1.5
appVersion: "1.1.5"
home: https://github.com/clm-cloud-solutions/kubebolt
icon: https://raw.githubusercontent.com/clm-cloud-solutions/kubebolt/main/docs/images/kubebolt-icon.png
sources:
  - https://github.com/clm-cloud-solutions/kubebolt
maintainers:
  - name: clm-cloud-solutions
    url: https://github.com/clm-cloud-solutions
keywords:
  - kubernetes
  - monitoring
  - observability
  - agent
  - daemonset
  - cilium
  - hubble
  - kubebolt
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: GitHub
      url: https://github.com/clm-cloud-solutions/kubebolt
  artifacthub.io/containsSecurityUpdates: "true"
