package copilot

import (
	"context"
	"fmt"
	"strings"

	"github.com/kubebolt/kubebolt/apps/api/internal/config"
)

// CompactResult describes a compaction outcome.
type CompactResult struct {
	Summary      string  // the generated summary text
	NewMessages  []Message // messages array to use going forward
	TokensBefore int     // approx tokens before compaction
	TokensAfter  int     // approx tokens after compaction
	TurnsFolded  int     // how many turns got replaced by the summary
	UsedModel    string  // model actually used for the summarization call
	Usage        Usage   // tokens consumed by the summarization call itself
}

// CompactOptions controls a Compact() call.
type CompactOptions struct {
	// PreserveTurns is how many of the last user-text turns (and everything
	// after them) stay intact. The rest gets folded into a summary.
	PreserveTurns int
	// Provider used for the primary chat; compaction reuses the same vendor
	// but substitutes a cheaper model when CompactModel is empty.
	Provider config.ProviderConfig
	// CompactModel overrides the cheap-model auto-pick.
	CompactModel string
	// ResetAll, when true, folds ALL turns into a summary — used by the
	// manual "new session with summary" flow. PreserveTurns is ignored.
	ResetAll bool
}

// Compact folds older turns of a conversation into a single assistant
// summary message, preserving the last PreserveTurns turns intact. The
// summary is generated by a cheap-tier model of the same provider so the
// compaction itself doesn't burn expensive tokens.
//
// If fewer than PreserveTurns+1 turns exist, Compact returns the original
// messages unchanged — nothing to compact yet.
func Compact(ctx context.Context, msgs []Message, opts CompactOptions) (*CompactResult, error) {
	// Locate turn starts from the end
	turnStarts := []int{}
	for i := len(msgs) - 1; i >= 0; i-- {
		if msgs[i].Role == RoleUser && len(msgs[i].ToolResults) == 0 && msgs[i].Content != "" {
			turnStarts = append(turnStarts, i)
		}
	}
	if len(turnStarts) == 0 {
		return nil, fmt.Errorf("no user turns found to compact")
	}

	var cutoff int
	if opts.ResetAll {
		cutoff = len(msgs)
	} else {
		if len(turnStarts) <= opts.PreserveTurns {
			// Not enough to compact; caller should have checked but we're defensive.
			return &CompactResult{
				Summary:      "",
				NewMessages:  msgs,
				TokensBefore: ApproxTokens(msgs),
				TokensAfter:  ApproxTokens(msgs),
				TurnsFolded:  0,
			}, nil
		}
		cutoff = turnStarts[opts.PreserveTurns-1]
	}

	oldMsgs := msgs[:cutoff]
	tail := []Message{}
	if !opts.ResetAll {
		tail = msgs[cutoff:]
	}

	// Pick model
	compactModel := opts.CompactModel
	if compactModel == "" {
		compactModel = CheapModelFor(opts.Provider.Provider)
	}
	compactProvider := opts.Provider
	if compactModel != "" {
		compactProvider.Model = compactModel
	}

	// Build summarization request. We render the old conversation as plain
	// text (role-prefixed) inside a single user message, ask for a structured
	// summary back.
	transcript := renderTranscript(oldMsgs)
	sysPrompt := "You are a terse technical summarizer for a Kubernetes copilot session. " +
		"Preserve: the cluster / namespace / resources under investigation, user intent, " +
		"findings (symptoms, root causes), actions taken, and any pending questions. " +
		"Drop: pleasantries, full tool outputs, redundant restatements. " +
		"Output a compact bulleted summary in English under 400 words."

	userMsg := Message{
		Role:    RoleUser,
		Content: "Summarize this conversation so it can continue without losing context:\n\n" + transcript,
	}

	provider := GetProvider(compactProvider.Provider)
	if provider == nil {
		return nil, fmt.Errorf("unknown compaction provider %q", compactProvider.Provider)
	}

	resp, err := provider.Chat(ctx, ChatRequest{
		System:    sysPrompt,
		Messages:  []Message{userMsg},
		Provider:  compactProvider,
		MaxTokens: 1024,
	})
	if err != nil {
		return nil, fmt.Errorf("compaction LLM call failed: %w", err)
	}
	if strings.TrimSpace(resp.Text) == "" {
		return nil, fmt.Errorf("compaction returned empty summary")
	}

	summaryMsg := Message{
		Role:    RoleAssistant,
		Content: "[Compacted conversation summary]\n" + strings.TrimSpace(resp.Text),
	}

	var newMsgs []Message
	if opts.ResetAll {
		newMsgs = []Message{summaryMsg}
	} else {
		newMsgs = make([]Message, 0, 1+len(tail))
		newMsgs = append(newMsgs, summaryMsg)
		newMsgs = append(newMsgs, tail...)
	}

	return &CompactResult{
		Summary:      resp.Text,
		NewMessages:  newMsgs,
		TokensBefore: ApproxTokens(msgs),
		TokensAfter:  ApproxTokens(newMsgs),
		TurnsFolded:  countTurns(oldMsgs),
		UsedModel:    compactModel,
		Usage:        resp.Usage,
	}, nil
}

func renderTranscript(msgs []Message) string {
	var b strings.Builder
	for _, m := range msgs {
		switch m.Role {
		case RoleUser:
			if len(m.ToolResults) > 0 {
				b.WriteString("[tool_results: ")
				for i, tr := range m.ToolResults {
					if i > 0 {
						b.WriteString(", ")
					}
					b.WriteString(fmt.Sprintf("%s (%d chars)", tr.ToolCallID, len(tr.Content)))
				}
				b.WriteString("]\n")
				continue
			}
			if m.Content != "" {
				b.WriteString("user: ")
				b.WriteString(m.Content)
				b.WriteString("\n")
			}
		case RoleAssistant:
			if m.Content != "" {
				b.WriteString("assistant: ")
				b.WriteString(m.Content)
				b.WriteString("\n")
			}
			if len(m.ToolCalls) > 0 {
				for _, tc := range m.ToolCalls {
					b.WriteString(fmt.Sprintf("assistant [tool_call: %s]\n", tc.Name))
				}
			}
		}
	}
	return b.String()
}

func countTurns(msgs []Message) int {
	n := 0
	for _, m := range msgs {
		if m.Role == RoleUser && len(m.ToolResults) == 0 && m.Content != "" {
			n++
		}
	}
	return n
}
