package copilot

import (
	"context"
	"fmt"
	"strings"

	"github.com/kubebolt/kubebolt/apps/api/internal/config"
)

// CompactResult describes a compaction outcome.
type CompactResult struct {
	Summary      string    // the generated summary text (empty when only stubbing happened)
	NewMessages  []Message // messages array to use going forward
	TokensBefore int       // approx tokens before compaction
	TokensAfter  int       // approx tokens after compaction
	TurnsFolded  int       // how many turns got replaced by the summary
	ToolResultsStubbed int // how many tool_result blocks had their content replaced by a stub
	UsedModel    string    // model actually used for the summarization call
	Usage        Usage     // tokens consumed by the summarization call itself
}

// CompactOptions controls a Compact() call.
type CompactOptions struct {
	// PreserveTurns is how many of the last user-text turns (and everything
	// after them) stay intact. The rest gets folded into a summary.
	PreserveTurns int
	// Provider used for the primary chat; compaction reuses the same vendor
	// but substitutes a cheaper model when CompactModel is empty.
	Provider config.ProviderConfig
	// CompactModel overrides the cheap-model auto-pick.
	CompactModel string
	// ResetAll, when true, folds ALL turns into a summary — used by the
	// manual "new session with summary" flow. PreserveTurns is ignored.
	ResetAll bool
}

// Compact folds older turns of a conversation into a single assistant
// summary message, preserving the last PreserveTurns turns intact. The
// summary is generated by a cheap-tier model of the same provider so the
// compaction itself doesn't burn expensive tokens.
//
// When there aren't enough turns to fold a summary (len(turnStarts) ≤
// PreserveTurns) but the conversation is still heavy, Compact falls back
// to stubbing tool_results in place so the next request carries only the
// reasoning chain, not the raw data. In the normal path it also stubs
// tool_results in the preserved tail — the bulky data usually lives in
// the most recent turns, so folding old turns alone rarely saves much.
//
// The LLM can always re-fetch data by calling the tool again.
func Compact(ctx context.Context, msgs []Message, opts CompactOptions) (*CompactResult, error) {
	// Locate turn starts from the end
	turnStarts := []int{}
	for i := len(msgs) - 1; i >= 0; i-- {
		if msgs[i].Role == RoleUser && len(msgs[i].ToolResults) == 0 && msgs[i].Content != "" {
			turnStarts = append(turnStarts, i)
		}
	}
	if len(turnStarts) == 0 {
		return nil, fmt.Errorf("no user turns found to compact")
	}

	beforeTokens := ApproxTokens(msgs)

	// Fallback path: can't produce a summary (not enough turns) but we can
	// still free the bulk by stubbing tool_results in earlier turns. The
	// currently-executing turn (from the last user-text message onward)
	// is protected — its tool_results are what the LLM is reading right
	// now, stubbing them would truncate the response.
	if !opts.ResetAll && len(turnStarts) <= opts.PreserveTurns {
		stubbed, count := stubToolResults(msgs, activeTurnStart(msgs))
		return &CompactResult{
			Summary:            "",
			NewMessages:        stubbed,
			TokensBefore:       beforeTokens,
			TokensAfter:        ApproxTokens(stubbed),
			TurnsFolded:        0,
			ToolResultsStubbed: count,
		}, nil
	}

	var cutoff int
	if opts.ResetAll {
		cutoff = len(msgs)
	} else {
		cutoff = turnStarts[opts.PreserveTurns-1]
	}

	oldMsgs := msgs[:cutoff]
	tail := []Message{}
	if !opts.ResetAll {
		tail = msgs[cutoff:]
	}

	// Pick model
	compactModel := opts.CompactModel
	if compactModel == "" {
		compactModel = CheapModelFor(opts.Provider.Provider)
	}
	compactProvider := opts.Provider
	if compactModel != "" {
		compactProvider.Model = compactModel
	}

	// Build summarization request. We render the old conversation as plain
	// text (role-prefixed) inside a single user message, ask for a structured
	// summary back.
	transcript := renderTranscript(oldMsgs)
	sysPrompt := "You are a terse technical summarizer for a Kubernetes copilot session. " +
		"Preserve: the cluster / namespace / resources under investigation, user intent, " +
		"findings (symptoms, root causes), actions taken, and any pending questions. " +
		"Drop: pleasantries, full tool outputs, redundant restatements. " +
		"Output a compact bulleted summary in English under 400 words."

	userMsg := Message{
		Role:    RoleUser,
		Content: "Summarize this conversation so it can continue without losing context:\n\n" + transcript,
	}

	provider := GetProvider(compactProvider.Provider)
	if provider == nil {
		return nil, fmt.Errorf("unknown compaction provider %q", compactProvider.Provider)
	}

	resp, err := provider.Chat(ctx, ChatRequest{
		System:    sysPrompt,
		Messages:  []Message{userMsg},
		Provider:  compactProvider,
		MaxTokens: 1024,
	})
	if err != nil {
		return nil, fmt.Errorf("compaction LLM call failed: %w", err)
	}
	if strings.TrimSpace(resp.Text) == "" {
		return nil, fmt.Errorf("compaction returned empty summary")
	}

	summaryMsg := Message{
		Role:    RoleAssistant,
		Content: "[Compacted conversation summary]\n" + strings.TrimSpace(resp.Text),
	}

	// Stub tool_results in the preserved tail — the heavy data usually
	// lives here, not in the folded history. The compact already breaks
	// the prompt cache (new prefix via the summary), so losing the tail's
	// cached tool_result bytes adds no extra cost. The LLM keeps the user
	// text, assistant text and tool_call metadata intact.
	//
	// CRITICAL: skip tool_results belonging to the active turn (from the
	// last user-text message onward). Those are what the LLM is about to
	// read in the next round — stubbing them breaks the response.
	stubbedCount := 0
	var preservedTail []Message
	if !opts.ResetAll && len(tail) > 0 {
		// activeTurnStart is absolute over msgs; make it relative to tail.
		activeAbs := activeTurnStart(msgs)
		protectInTail := activeAbs - cutoff
		if protectInTail < 0 {
			protectInTail = 0
		}
		if protectInTail > len(tail) {
			protectInTail = len(tail)
		}
		preservedTail, stubbedCount = stubToolResults(tail, protectInTail)
	}

	var newMsgs []Message
	if opts.ResetAll {
		newMsgs = []Message{summaryMsg}
	} else {
		newMsgs = make([]Message, 0, 1+len(preservedTail))
		newMsgs = append(newMsgs, summaryMsg)
		newMsgs = append(newMsgs, preservedTail...)
	}

	return &CompactResult{
		Summary:            resp.Text,
		NewMessages:        newMsgs,
		TokensBefore:       beforeTokens,
		TokensAfter:        ApproxTokens(newMsgs),
		TurnsFolded:        countTurns(oldMsgs),
		ToolResultsStubbed: stubbedCount,
		UsedModel:          compactModel,
		Usage:              resp.Usage,
	}, nil
}

func renderTranscript(msgs []Message) string {
	var b strings.Builder
	for _, m := range msgs {
		switch m.Role {
		case RoleUser:
			if len(m.ToolResults) > 0 {
				b.WriteString("[tool_results: ")
				for i, tr := range m.ToolResults {
					if i > 0 {
						b.WriteString(", ")
					}
					b.WriteString(fmt.Sprintf("%s (%d chars)", tr.ToolCallID, len(tr.Content)))
				}
				b.WriteString("]\n")
				continue
			}
			if m.Content != "" {
				b.WriteString("user: ")
				b.WriteString(m.Content)
				b.WriteString("\n")
			}
		case RoleAssistant:
			if m.Content != "" {
				b.WriteString("assistant: ")
				b.WriteString(m.Content)
				b.WriteString("\n")
			}
			if len(m.ToolCalls) > 0 {
				for _, tc := range m.ToolCalls {
					b.WriteString(fmt.Sprintf("assistant [tool_call: %s]\n", tc.Name))
				}
			}
		}
	}
	return b.String()
}

func countTurns(msgs []Message) int {
	n := 0
	for _, m := range msgs {
		if m.Role == RoleUser && len(m.ToolResults) == 0 && m.Content != "" {
			n++
		}
	}
	return n
}

// stubToolResults returns a copy of msgs where every ToolResult's Content
// is replaced by a short placeholder that preserves ToolCallID and IsError.
// Used inside Compact to free the bulk of preserved turns whose raw data
// the LLM can re-fetch if it actually needs it. Returns the count of
// tool_result blocks that were replaced.
//
// Only stubs when the original content is large enough to be worth it —
// small results (<256 chars) are kept verbatim because replacing them
// would actually grow the payload thanks to the stub wording.
//
// Messages at indexes >= protectFrom are NEVER stubbed. That range
// belongs to the currently-executing turn whose tool_results the LLM is
// actively processing — stubbing them would make the LLM respond with
// "output was truncated" because it sees placeholders instead of the
// raw data it requested.
func stubToolResults(msgs []Message, protectFrom int) ([]Message, int) {
	const minBytesToStub = 256

	out := make([]Message, len(msgs))
	stubbed := 0
	for i, m := range msgs {
		if i >= protectFrom || len(m.ToolResults) == 0 {
			out[i] = m
			continue
		}
		anyStubbed := false
		elided := make([]ToolResult, len(m.ToolResults))
		for j, tr := range m.ToolResults {
			if len(tr.Content) < minBytesToStub {
				elided[j] = tr
				continue
			}
			elided[j] = ToolResult{
				ToolCallID: tr.ToolCallID,
				Content: fmt.Sprintf(
					"[tool result stubbed during compact; original %d chars. Call the tool again if you need the full data.]",
					len(tr.Content),
				),
				IsError: tr.IsError,
			}
			stubbed++
			anyStubbed = true
		}
		if anyStubbed {
			out[i] = Message{
				Role:        m.Role,
				Content:     m.Content,
				ToolCalls:   m.ToolCalls,
				ToolResults: elided,
			}
		} else {
			out[i] = m
		}
	}
	return out, stubbed
}

// activeTurnStart returns the index of the most recent user-text message
// in msgs, or len(msgs) when no such message exists. Tool_results at or
// after this index belong to the currently-executing turn and must not
// be stubbed by compaction — the LLM hasn't yet processed them.
func activeTurnStart(msgs []Message) int {
	for i := len(msgs) - 1; i >= 0; i-- {
		if msgs[i].Role == RoleUser && len(msgs[i].ToolResults) == 0 && msgs[i].Content != "" {
			return i
		}
	}
	return len(msgs)
}
