apiVersion: v2
name: kubebolt
description: Instant Kubernetes Monitoring & Management — full cluster visibility in under 2 minutes
type: application
version: 1.8.0
appVersion: "1.8.0"
home: https://github.com/clm-cloud-solutions/kubebolt
icon: https://raw.githubusercontent.com/clm-cloud-solutions/kubebolt/main/docs/images/kubebolt-icon.png
sources:
  - https://github.com/clm-cloud-solutions/kubebolt
maintainers:
  - name: clm-cloud-solutions
    url: https://github.com/clm-cloud-solutions
keywords:
  - kubernetes
  - monitoring
  - observability
  - dashboard
  - kubectl
  - management
  - rbac
  - multi-cluster
  - gateway-api
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: GitHub
      url: https://github.com/clm-cloud-solutions/kubebolt
  artifacthub.io/containsSecurityUpdates: "false"
